apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc  # nom de la ressource (référencé par le Deployment)
spec:
  # accessModes : qui peut monter ce volume
  # ReadWriteOnce : un seul nœud à la fois en lecture/écriture (suffisant ici)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # demande 2 Go de stockage